# documentation: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference
version: 2
updates:
  # keep GitHub Actions used in workflows (which are pinned to a specific commit) up-to-date
  - package-ecosystem: github-actions
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
