#!/usr/bin/env python
# #
# Copyright 2009-2014 Ghent University
#
# This file is part of EasyBuild,
# originally created by the HPC team of Ghent University (http://ugent.be/hpc/en),
# with support of Ghent University (http://ugent.be/hpc),
# the Flemish Supercomputer Centre (VSC) (https://vscentrum.be/nl/en),
# the Hercules foundation (http://www.herculesstichting.be/in_English)
# and the Department of Economy, Science and Innovation (EWI) (http://www.ewi-vlaanderen.be/en).
#
# http://github.com/hpcugent/easybuild
#
# EasyBuild is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation v2.
#
# EasyBuild is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EasyBuild.  If not, see <http://www.gnu.org/licenses/>.
# #
"""
Module which allows the diffing of multiple files

@author: Toon Willems (Ghent University)
"""

import difflib
import math
import os
import sys

import easybuild.tools.terminal as terminal

GREEN = "\033[0;32m"
PURPLE = "\033[0;35m"
RED = "\033[0;21m"
ENDC = "\033[0m"
B_GREEN = "\033[0;42m"
B_RED = "\033[0;41m"

class MultiDiff(object):
    """
    This class holds the diff information
    """

    REMOVED_KEY = 'removed'
    ADDED_KEY = 'added'

    def __init__(self, base, files, colored=True):
        self.base = base
        self.base_lines = open(base).readlines()
        self.diff_info = dict()
        self.files = files
        self.colored = colored

    def parse_line(self,line_no, diff_line, meta, squigly_line=None):
        """
        Parse a line as generated by difflib
        """
        if diff_line.startswith('+'):
            key = self.ADDED_KEY
        elif diff_line.startswith('-'):
            key = self.REMOVED_KEY

        self.diff_info.setdefault(line_no, {}).setdefault(key,[]).append((diff_line.rstrip(), meta, squigly_line))

    def __str__(self):
        """
        Create a string representation of this multi diff
        """
        def limit(text, length):
            """ limit text to certain length, add ENDC if needd """
            if len(text) > length:
                return text[0:length-3] + ENDC + '...'
            else:
                return text

        output = []

        w,h = terminal.get_terminal_size()
        output.append(" ".join(["Comparing", self._color(os.path.basename(self.base), PURPLE), "with",
                                ", ".join(map(os.path.basename,self.files))]))

        for i in range(len(self.base_lines)):
            lines = filter(None,self.get_line(i))

            if lines:
                output.append("\n".join([limit(line,w) for line in lines]))

        return "\n".join(output)

    def get_line(self, line_no):
        """
        Return the line information for a specific line
        """
        output = []
        diff_dict = self.diff_info.get(line_no, {})
        for key in [self.REMOVED_KEY, self.ADDED_KEY]:
            lines = set()
            changes_dict = dict()
            squigly_dict = dict()

            if key in diff_dict:
                for (diff_line, meta, squigly_line) in diff_dict[key]:
                    if squigly_line:
                        squigly_line2 = squigly_dict.get(diff_line, squigly_line)
                        squigly_dict[diff_line] = self._merge_squigly(squigly_line, squigly_line2)
                    lines.add(diff_line)
                    changes_dict.setdefault(diff_line,set()).add(meta)

            # restrict displaying of removals to max_groups
            max_groups = 2
            # sort highest first
            lines = sorted(lines, key=lambda line: len(changes_dict[line]))
            # limit to max_groups
            lines = lines[::-1][:max_groups]

            for diff_line in lines:
                line = [str(line_no)]
                squigly_line = squigly_dict.get(diff_line,'')
                line.append(self._colorize(diff_line, squigly_line))

                files = changes_dict[diff_line]
                num_files = len(self.files)

                line.append("(%d/%d)" % (len(files), num_files))
                if len(files) != num_files:
                        line.append(', '.join(files))

                output.append(" ".join(line))
                # prepend spaces to match line number length
                if not self.colored and squigly_line:
                    prepend = ' ' * (2 + int(math.log10(line_no)))
                    output.append(''.join([prepend,squigly_line]))

        # print seperator only if needed
        if diff_dict and not self.diff_info.get(line_no + 1, {}):
            output.extend([' ', '-----', ' '])

        return output

    def _colorize(self, line, squigly):
        """Add colors to the diff line based on the squiqly line"""
        if not self.colored:
            return line

        chars = list(line)
        flag = ' '
        compensator = 0
        color_map = {'-': B_RED, '+': B_GREEN, '^': B_GREEN if line.startswith('+') else B_RED}
        if squigly:
            for i,s in enumerate(squigly):
                if s != flag:
                    chars.insert(i + compensator, ENDC)
                    compensator += 1
                    if s in ('+','-','^'):
                        chars.insert(i + compensator, color_map.get(s, ''))
                        compensator += 1
                    flag = s
            chars.insert(len(squigly)+compensator, ENDC)
        else:
            chars.insert(0, color_map.get(line[0],''))
            chars.append(ENDC)



        return ''.join(chars)

    def _color(self, line, color):
        if self.colored:
            return ''.join([color, line, ENDC])
        else:
            return line

    def _merge_squigly(self, squigly1, squigly2):
        """Combine 2 diff lines into 1 """
        sq1 = list(squigly1)
        sq2 = list(squigly2)
        base,other = (sq1, sq2) if len(sq1) > len(sq2) else (sq2,sq1)

        for i,o in enumerate(other):
            if base[i] in (' ', '^') and base[i] != o:
                base[i]=o

        return ''.join(base)

def multi_diff(base,files, colored=True):
    """
    generate a Diff for multiple files, all compared to base
    """
    d = difflib.Differ()
    differ = MultiDiff(base, files, colored)

    base_lines = differ.base_lines

    # use the Diff class to store the information
    for file_name in files:
        diff = list(d.compare(open(file_name).readlines(), base_lines))
        file_name = os.path.basename(file_name)

        local_diff = dict()
        squigly_dict = dict()
        last_added = None
        compensator = 1
        for (i, line) in enumerate(diff):
            if line.startswith('?'):
                squigly_dict[last_added] = (line)
                compensator -= 1
            elif line.startswith('+'):
                local_diff.setdefault(i+compensator, []).append((line, file_name))
                last_added = line
            elif line.startswith('-'):
                local_diff.setdefault(i+compensator, []).append((line, file_name))
                last_added = line
                compensator -= 1

        # construct the Diff based on the above dict
        for line_no in local_diff:
            for (line, file_name) in local_diff[line_no]:
                differ.parse_line(line_no, line, file_name, squigly_dict.get(line, '').rstrip())

    return differ
