name: Static Analysis
on: [push, pull_request]

permissions:
  contents: read # to fetch code (actions/checkout)

concurrency:
  group: ${{format('{0}:{1}:{2}', github.repository, github.ref, github.workflow)}}
  cancel-in-progress: true

jobs:
  python-linting:
    strategy:
      matrix:
        python: [3.8, 3.9, '3.10', '3.11']
        include:
          - python: 3.7
            os: ubuntu-22.04
      fail-fast: false
    runs-on: ${{matrix.os || 'ubuntu-24.04'}}

    steps:
    - uses: actions/checkout@v4

    - name: set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: install Python packages
      run: |
        pip install --upgrade pip
        pip install --upgrade flake8

    - name: Run flake8 to verify PEP8-compliance of Python code
      run: |
        # don't check py2vs3/py3.py when testing with Python 2, and vice versa
        if [[ "${{ matrix.python-version }}" =~ "2." ]]; then
            py_excl=py3
        else
            py_excl=py2
        fi
        flake8 --exclude ./easybuild/tools/py2vs3/${py_excl}.py
