name: Static Analysis
on: [push, pull_request]

permissions:
  contents: read # to fetch code (actions/checkout)

concurrency:
  group: ${{format('{0}:{1}:{2}', github.repository, github.ref, github.workflow)}}
  cancel-in-progress: true

jobs:
  python-linting:
    strategy:
      matrix:
        # only lint with oldest and most recent supported Python version,
        # that's sufficient to catch syntax that is not supported by older/newer Python versions
        python: ['3.14']
        include:
          - python: 3.7
            os: ubuntu-22.04
      fail-fast: false
    runs-on: ${{matrix.os || 'ubuntu-24.04'}}
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # 7.0.0

    - name: set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: ${{ matrix.python }}

    - name: install Python packages
      run: |
        pip install --upgrade pip
        # use pinned versions of linting tools, see requirements-lint.txt
        pip install -r requirements-lint.txt

    - name: Run flake8 to verify PEP8-compliance of Python code
      run: |
        flake8
